service: wp-cdn
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  logRetentionInDays: 14
  stage: prod
  region: us-east-1
  stackTags:
    Service: ${param:servicePrefix}
    Stack: ${self:service}
    Stage: ${sls:stage}
    Name: ${self:service}

params:
  default:
    servicePrefix: wp
    domain: # e.g. wp.example.com
    appServerHostname: server
    wordPressDomainAlias: wordpress.${param:domain}
    sslCertificateArn: # e.g. arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/GUID

resources: ${file(./resources.yml)}
